"""W3 Step 7: the two reading samples.

  w3_trace_sample.md     10 form-B incentive traces, fixed indices 0/10/20/30/40 per
                         condition, with the frozen parser's intermediates tau-echo-marked.
  w3_direction_sample.md 10 direction-judge verdicts, fixed indices 0-4 per condition on
                         form A, each printed beside the trace text it judged, so the
                         researcher can validate the judge rather than trust it.

Both index rules are positional and fixed here before any content was read. An index that is
invalid (truncated, or empty visible answer) advances to index+1 and every substitution is
printed in the header.

  python3 src/samples_w3.py --tau-a 15300000 --tau-b <tau_B>
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
import extract_regex as ex  # noqa: E402

FROZEN = ROOT / "runs" / "w3_frozen"
OUT_TRACE = ROOT / "analysis" / "out" / "w3_trace_sample.md"
OUT_DIRS = ROOT / "analysis" / "out" / "w3_direction_sample.md"
DIR_CACHE = ROOT / "analysis" / "out" / "w3_direction_cache.json"
MODEL = "Qwen/Qwen2.5-14B-Instruct"
CONDS = ("below_good", "above_good")
TRACE_IDX = (0, 10, 20, 30, 40)      # fixed by the W3 order
DIR_IDX = (0, 1, 2, 3, 4)            # fixed by the W3 order


def fmt(v):
    if v is None:
        return "None"
    return ("%d" % v) if float(v).is_integer() else ("%g" % v)


def valid(r):
    return (not r["truncated"]) and bool((r["visible_answer"] or "").strip())


def pick(rows, idx0, subs, label):
    idx = idx0
    while idx in rows and not valid(rows[idx]):
        subs.append("%s index %d invalid (truncated=%s) -> took %d"
                    % (label, idx, rows[idx]["truncated"], idx + 1))
        idx += 1
    return idx, rows.get(idx)


def trace_sample(tau_b):
    subs, body = [], []
    for cond in CONDS:
        d = json.loads((FROZEN / "form_B" / ("%s.json" % cond)).read_text())
        rows = {r["i"]: r for r in d["rows"]}
        body += ["", "---", "", "## form B · condition `%s`" % cond, "",
                 "- threshold as rendered to the model: `%s`" % d["threshold_formatted"],
                 "- seeds %d–%d · sampling `%s`"
                 % (d["rows"][0]["seed"], d["rows"][-1]["seed"], json.dumps(d["sampling"])),
                 "- truncated in this arm: %d / %d" % (d["n_truncated"], d["n"]), ""]
        for i0 in TRACE_IDX:
            idx, r = pick(rows, i0, subs, "form B %s" % cond)
            if r is None:
                body += ["### rollout %d — NOT PRESENT" % idx, ""]
                continue
            raw = ex.intermediates(r["reasoning_text"])
            marks = []
            for v in raw:
                s = "ABOVE" if v > tau_b else "BELOW"
                echo = " **[τ-ECHO]**" if v == tau_b else ""
                off = "" if (tau_b / 100.0) <= v <= (tau_b * 100.0) else " [off-scale]"
                marks.append("%s (%s)%s%s" % (fmt(v), s, echo, off))
            noecho = [v for v in raw if v != tau_b]
            fin = ex.final_estimate(r["visible_answer"])
            body += ["### %s rollout %d (seed %d)%s"
                     % (cond, idx, r["seed"],
                        "" if idx == i0 else "  — substituted for invalid index %d" % i0), "",
                     "`finish_reason=%s` · `truncated=%s` · %d output tokens"
                     % (r["finish_reason"], r["truncated"], r["n_output_tokens"]), "",
                     "**Intermediates** — %d raw, %d after τ-echo exclusion, %d in-window:"
                     % (len(raw), len(noecho), len(ex.filtered(noecho, tau_b))), "",
                     "```", "\n".join("%2d. %s" % (k + 1, m) for k, m in enumerate(marks))
                     or "(none)", "```", "",
                     "**Final estimate (regex extractor):** `%s`%s" % (
                         fmt(fin), "  **[= τ exactly]**" if fin == tau_b else ""), "",
                     "<details><summary>full visible text</summary>", "",
                     "```", r["visible_answer"] or "(empty)", "```", "", "</details>", ""]
    head = ["# W3 form-B incentive trace sample", "",
            "Ten traces at **fixed rollout indices 0, 10, 20, 30, 40 from each condition**,",
            "fixed before any content was read. τ_B = **%s**." % "{:,}".format(int(tau_b)), "",
            "Each intermediate is marked `ABOVE`/`BELOW` (strict PR-001 item 6), flagged",
            "**[τ-ECHO]** when it equals τ exactly — R-008(2) excludes these from all",
            "activation-work estimate points — and `[off-scale]` when outside `[τ/100, 100τ]`.",
            "",
            "Generated by `python3 src/samples_w3.py --tau-b %d`." % int(tau_b), "",
            "**Index substitutions:** " + ("; ".join(subs) if subs
                                           else "none — every fixed index was valid."), ""]
    OUT_TRACE.parent.mkdir(parents=True, exist_ok=True)
    OUT_TRACE.write_text("\n".join(head + body))
    return subs


def direction_sample():
    if not DIR_CACHE.exists():
        print("no direction cache yet — skipping", OUT_DIRS)
        return None
    dc = json.loads(DIR_CACHE.read_text())
    subs, body = [], []
    for cond in CONDS:
        d = json.loads((FROZEN / "form_A" / ("%s.json" % cond)).read_text())
        rows = {r["i"]: r for r in d["rows"]}
        body += ["", "---", "", "## form A · condition `%s`" % cond, "",
                 "The prompt these traces answered (threshold rendered `%s`):"
                 % d["threshold_formatted"], "",
                 "```", d["prompt_text"], "```", ""]
        for i0 in DIR_IDX:
            idx, r = pick(rows, i0, subs, "form A %s" % cond)
            if r is None:
                body += ["### rollout %d — NOT PRESENT" % idx, ""]
                continue
            v = dc.get("%s|A|%s|%d" % (MODEL, cond, idx))
            body += ["### %s rollout %d (seed %d)%s"
                     % (cond, idx, r["seed"],
                        "" if idx == i0 else "  — substituted for invalid index %d" % i0), "",
                     "**Judge verdict:** `mentions_bet=%s` · `direction=%s`"
                     % (None if not v else v["mentions_bet"],
                        None if not v else v["direction"]), "",
                     "<details><summary>judge raw reply</summary>", "",
                     "```", (v or {}).get("raw", "(not judged)"), "```", "", "</details>", "",
                     "**The trace the judge read, in full:**", "",
                     "```", r["visible_answer"] or "(empty)", "```", ""]
    head = ["# W3 direction-judge validation sample", "",
            "Ten verdicts at **fixed rollout indices 0–4 from each form-A condition**, fixed",
            "before any content was read. Each verdict is printed **beside the trace it**",
            "**judged and the prompt that trace answered**, so the researcher can check the",
            "judge rather than trust it. The judge prompt is frozen verbatim in PR-003 item 5.",
            "",
            "`direction=correct` means the response's stated understanding of which side",
            "favours the good cause matches its own prompt — **not** that its estimate is good.",
            "",
            "Generated by `python3 src/samples_w3.py`.", "",
            "**Index substitutions:** " + ("; ".join(subs) if subs
                                           else "none — every fixed index was valid."), ""]
    OUT_DIRS.write_text("\n".join(head + body))
    return subs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tau-a", type=int, default=15300000)
    ap.add_argument("--tau-b", type=int, required=True)
    args = ap.parse_args()
    s1 = trace_sample(args.tau_b)
    print("wrote", OUT_TRACE, "| indices", list(TRACE_IDX), "| substitutions:", s1 or "none")
    s2 = direction_sample()
    if s2 is not None:
        print("wrote", OUT_DIRS, "| indices", list(DIR_IDX), "| substitutions:", s2 or "none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
