"""W1 Step 6: the researcher's reading sample.

Two full neutral traces per model at FIXED indices 0 and 25 — no cherry-picking, no
selection on content — with the parser's extracted intermediate sequence and final
printed beneath each, so the parses can be checked against the text by eye.

  python3 src/trace_sample.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
import extract_regex as ex  # noqa: E402

INDICES = (0, 25)          # fixed by the W1 order; applied blind
NEUTRAL_ROOT = ROOT / "runs" / "w1_neutral"
OUT = ROOT / "analysis" / "out" / "w1_trace_sample.md"


def fmt(v):
    if v is None:
        return "None"
    return ("%d" % v) if float(v).is_integer() else ("%g" % v)


def main():
    dirs = sorted(d for d in NEUTRAL_ROOT.iterdir() if d.is_dir())
    if not dirs:
        print("no neutral runs under", NEUTRAL_ROOT)
        return 1

    L = ["# W1 neutral trace sample",
         "",
         "Two traces per model at **fixed rollout indices 0 and 25**, selected before any",
         "content was read — the rule is positional, so nothing here is cherry-picked. Under",
         "each trace: the intermediate sequence from the frozen PR-001 item 9 parser, and the",
         "final estimate from the PR-001 item 8 regex extractor.",
         "",
         "Generated by `python3 src/trace_sample.py`.",
         ""]

    for d in dirs:
        data = json.loads((d / "neutral.json").read_text())
        rows = {r["i"]: r for r in data["rows"]}
        L += ["", "---", "", "## %s" % data["model"],
              "", "- family split mode: `%s`" % data["family_mode"],
              "- sampling: `%s`" % json.dumps(data["sampling"]),
              "- truncated in this run: %d / %d" % (data["n_truncated"], data["n"]), ""]

        for idx in INDICES:
            r = rows.get(idx)
            if r is None:
                L += ["### rollout %d — NOT PRESENT" % idx, ""]
                continue
            seq = ex.intermediates(r["reasoning_text"])
            fin = ex.final_estimate(r["visible_answer"])
            L += ["### rollout %d (seed %d)" % (idx, r["seed"]),
                  "",
                  "`finish_reason=%s` · `truncated=%s` · %d output tokens · split via `%s`"
                  % (r["finish_reason"], r["truncated"], r["n_output_tokens"],
                     r["split_method"]),
                  "",
                  "**Parser output** — %d intermediates: `[%s]`"
                  % (len(seq), ", ".join(fmt(v) for v in seq)),
                  "",
                  "**Final estimate (regex extractor):** `%s`" % fmt(fin),
                  "",
                  "<details><summary>reasoning text (full)</summary>", "",
                  "```", r["reasoning_text"] or "(empty)", "```", "", "</details>", "",
                  "<details><summary>visible answer (full)</summary>", "",
                  "```", r["visible_answer"] or "(empty)", "```", "", "</details>", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L))
    print("wrote", OUT, "(%d models, indices %s)" % (len(dirs), list(INDICES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
