"""W2 Step 5: the researcher's reading sample for the gated model.

Ten incentive traces at FIXED indices 0, 10, 20, 30, 40 from each of the two conditions,
chosen before any content was read. If an index is invalid (truncated, or no visible
answer) the order says take index+1; every such substitution is printed in the header.

Under each trace: the frozen PR-001 item-9 intermediate sequence with each estimate
marked ABOVE (>tau) or BELOW (<=tau), and flagged if it falls outside the [tau/100,
100*tau] filter window; then the final from the item-8 regex extractor; then the full
reasoning text.

  python3 src/trace_sample_w2.py --model Qwen/Qwen3-8B --tau 31250000
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
import extract_regex as ex  # noqa: E402

INDICES = (0, 10, 20, 30, 40)      # fixed by the W2 order; applied blind
CONDITIONS = ("below_good", "above_good")
OUT = ROOT / "analysis" / "out" / "w2_trace_sample.md"


def fmt(v):
    if v is None:
        return "None"
    return ("%d" % v) if float(v).is_integer() else ("%g" % v)


def valid(r):
    return (not r["truncated"]) and bool((r["visible_answer"] or "").strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--tau", type=int, required=True)
    ap.add_argument("--screen-root", default=str(ROOT / "runs" / "w2_screen"))
    args = ap.parse_args()
    tau, slug = args.tau, args.model.split("/")[-1]
    d = Path(args.screen_root) / slug

    subs = []
    L = ["# W2 incentive trace sample — %s" % args.model, "",
         "Ten traces: **fixed rollout indices 0, 10, 20, 30, 40 from each condition**, fixed",
         "before any content was read. The rule is positional, so nothing here is selected on",
         "what the trace says. tau = **%s** (W1 tau of record)." % "{:,}".format(tau), "",
         "Each intermediate is marked `ABOVE` (> tau) or `BELOW` (<= tau) under the strict",
         "PR-001 item-6 convention, and `[off-scale]` if it falls outside the",
         "`[tau/100, 100*tau]` window that R-007(1) pins G0's parse condition to.", "",
         "The researcher reads these to confirm the intermediates are genuine revisions rather",
         "than formatting artifacts. Generated by `python3 src/trace_sample_w2.py --model %s"
         " --tau %d`." % (args.model, tau), ""]

    body = []
    for cond in CONDITIONS:
        data = json.loads((d / ("%s.json" % cond)).read_text())
        rows = {r["i"]: r for r in data["rows"]}
        body += ["", "---", "", "## condition `%s`" % cond, "",
                 "- prompt threshold as rendered to the model: `%s`"
                 % data["threshold_formatted"],
                 "- family split mode: `%s`" % data["family_mode"],
                 "- sampling: `%s`" % json.dumps(data["sampling"]),
                 "- truncated in this run: %d / %d" % (data["n_truncated"], data["n"]), ""]
        for idx0 in INDICES:
            idx = idx0
            while idx in rows and not valid(rows[idx]):
                subs.append("%s index %d invalid (truncated=%s, empty answer=%s) -> took %d"
                            % (cond, idx, rows[idx]["truncated"],
                               not (rows[idx]["visible_answer"] or "").strip(), idx + 1))
                idx += 1
            r = rows.get(idx)
            if r is None:
                body += ["### rollout %d — NOT PRESENT" % idx, ""]
                continue
            seq = ex.intermediates(r["reasoning_text"])
            marks = []
            for v in seq:
                side = "ABOVE" if v > tau else "BELOW"
                off = "" if (tau / 100.0) <= v <= (tau * 100.0) else " [off-scale]"
                marks.append("%s (%s)%s" % (fmt(v), side, off))
            fin = ex.final_estimate(r["visible_answer"])
            fside = "-" if fin is None else ("ABOVE" if fin > tau else "BELOW")
            body += ["### %s rollout %d (seed %d)%s"
                     % (cond, idx, r["seed"], "" if idx == idx0 else
                        "  — substituted for invalid index %d" % idx0),
                     "",
                     "`finish_reason=%s` · `truncated=%s` · %d output tokens · split via `%s`"
                     % (r["finish_reason"], r["truncated"], r["n_output_tokens"],
                        r["split_method"]),
                     "",
                     "**Intermediate sequence** — %d raw, %d in-window:"
                     % (len(seq), len(ex.filtered(seq, tau))), "",
                     "```", "\n".join("%2d. %s" % (k + 1, m)
                                      for k, m in enumerate(marks)) or "(none)", "```", "",
                     "**Final estimate (regex extractor):** `%s` (%s)" % (fmt(fin), fside),
                     "",
                     "<details><summary>reasoning text (full)</summary>", "",
                     "```", r["reasoning_text"] or "(empty)", "```", "", "</details>", "",
                     "<details><summary>visible answer (full)</summary>", "",
                     "```", r["visible_answer"] or "(empty)", "```", "", "</details>", ""]

    L += ["**Index substitutions:** " + ("; ".join(subs) if subs else
                                         "none — every fixed index was valid."), ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L + body))
    print("wrote", OUT, "| indices", list(INDICES), "| substitutions:", subs or "none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
